version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    REPOSITORY_URI: "318098414972.dkr.ecr.ap-east-1.amazonaws.com/testing/nodejs"
    IMAGE_TAG: "latest"
    CONTAINER_NAME: "test-nodejs-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Checking for existing repository...
      - aws ecr describe-repositories --repository-names ${CONTAINER_NAME} || aws ecr create-repository --repository-name ${CONTAINER_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $CONTAINER_NAME .
      - docker tag $CONTAINER_NAME:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $CONTAINER_NAME:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json